### ISSUE TITLE
MTPerformModeLast下多线程野指针

### ISSUE THREAD

**Issue by lxlx5434** [yulingtianxia/MessageThrottle#12]
![bug](https://user-images.githubusercontent.com/11287332/51523162-00c63d00-1e66-11e9-8d49-fe8241662f7a.png)

见截图，多线程下lastInvocation在不同线程被修改，导致野指针crash。
需要保证messageQueue和mt_handleInvocation所在线程一致才能避免。

**Comment by yulingtianxia** [comment]
@lxlx5434 Fixed in 1.3.1 https://github.com/yulingtianxia/MessageThrottle/releases/tag/1.3.1

**Comment by lxlx5434** [comment]
> @lxlx5434 Fixed in 1.3.1 https://github.com/yulingtianxia/MessageThrottle/releases/tag/1.3.1

👍
