### ISSUE TITLE
请问为何限制同一个target的多个Rule

### ISSUE THREAD

**Issue by gssdromen** [yulingtianxia/MessageThrottle#13]
你好，我看到在应用Rule的函数里，target == rule.target限制了同一个target的多个Rule
	
	- (BOOL)applyRule:(MTRule *)rule
	{
	    pthread_mutex_lock(&mutex);
	    MTDealloc *mtDealloc = [rule mt_deallocObject];
	    [mtDealloc lock];
	    __block BOOL shouldApply = YES;
	    if (mt_checkRuleValid(rule)) {
	        for (id target in [[self.targetSELs keyEnumerator] allObjects]) {
	            if (target == rule.target) {
	                shouldApply = NO;
	                continue;
	            }
	            NSMutableSet *selectors = [self.targetSELs objectForKey:target];
	            for (NSString *selectorName in selectors) {
	                if (sel_isEqual(rule.selector, NSSelectorFromString(selectorName))
	                    && mt_object_isClass(rule.target)
	                    && mt_object_isClass(target)) {
	                    Class clsA = rule.target;
	                    Class clsB = target;
	                    shouldApply = !([clsA isSubclassOfClass:clsB] || [clsB isSubclassOfClass:clsA]) && shouldApply;
	                    NSLog(@"Sorry: %@ already apply rule in %@. A message can only have one rule per class hierarchy.", selectorName, NSStringFromClass(clsB));
	                }
	            }
	        }
	        shouldApply = shouldApply && mt_overrideMethod(rule);
	        if (shouldApply) {
	            [self addSelector:rule.selector onTarget:rule.target];
	            rule.active = YES;
	        }
	    }
	    else {
	        shouldApply = NO;
	    }
	    [mtDealloc unlock];
	    pthread_mutex_unlock(&mutex);
	    return shouldApply;
	}
	
	
导致我没法给同一个target的不同方法设置规则，请问是出于什么考虑？

	MTRule *debounceRule = [[MTRule alloc] initWithTarget:self selector:@selector(updateDebounceString:) durationThreshold:2];
    debounceRule.mode = MTPerformModeDebounce;
    [debounceRule apply];
    NSLog(@"%@", [self mt_allRules]);

    MTRule *throttleRule = [[MTRule alloc] initWithTarget:self selector:@selector(updateThrottlingString:) durationThreshold:2];
    throttleRule.mode = MTPerformModeLast;
    [throttleRule apply];

    NSLog(@"%@", [self mt_allRules]);

谢谢

**Comment by yulingtianxia** [comment]
@gssdromen 已经在 1.3.2 版本中修复。
https://github.com/yulingtianxia/MessageThrottle/releases/tag/1.3.2

**Comment by gssdromen** [comment]
thanks
