### ISSUE TITLE
只在iOS16的模拟器上crash

### ISSUE THREAD

**Issue by Rambo55555** [yulingtianxia/MessageThrottle#18]
0   CoreFoundation                      0x00007ff8004278cb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff800436ad8 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3                               0x000000010076ff6a mt_executeOrigForwardInvocation + 650
	4                               0x000000010076fabf mt_forwardInvocation + 735
	5   CoreFoundation                      0x00007ff80042bb28 ___forwarding___ + 814
	6   CoreFoundation                      0x00007ff80042e088 _CF_forwarding_prep_0 + 120

**Comment by yulingtianxia** [comment]
试了下没复现，方面发下复现的 demo 和操作路径么 @Rambo55555

**Comment by Rambo55555** [comment]
目前定位到是Xcode的iOS16模拟器的问题，这个问题只在英特尔芯片的电脑上的某个Xcode14版本下的iOS16模拟器会出现。而且这个“某个版本”很诡异，我从AppStore下载的最新Xcode14的iOS16模拟器会crash，而从官网下载的同一个版本则不会。demo没办法提供，操作路径是在一个线程里调用了限频方法。我尝试过在M1电脑上以 --arch=x86_64的方式启动模拟器，但是不会crash。考虑到是iOS16模拟器的问题，只能后面如果再出现再去解决了

**Comment by yulingtianxia** [comment]
好的，那我先 close 了
