### ISSUE TITLE
也许可以换一种调用方式

### ISSUE THREAD

**Issue by LionWY** [yulingtianxia/MessageThrottle#4]
为了更方便易用，可不可以在方法内部添加过滤限制，
```
- (IBAction)tapFoo:(UIButton *)sender {
    [self mt_limitSelector:_cmd oncePerDuration:0.5];
}
```
稍微改了下代码，应该可以实现的，就是第一次有问题，😄
纯粹个人习惯

**Comment by yulingtianxia** [comment]
这是啥，看不懂啊

**Comment by yulingtianxia** [comment]
@LionWY 明白了，是 Demo 的使用方式变成这样。但这只是其中一种场景，target 可以是实例对象，也可以是类对象，也可以是元类。所以作为演示 demo 还是要做的比较通用。

**Comment by LionWY** [comment]
不知道你看没看过这个，另外一种思路，不过确实挺 酷的
https://github.com/cyanzhong/GCDThrottle

**Comment by yulingtianxia** [comment]
@LionWY 功能用法上都不一样吧。钟大这个 GCDThrottle 看上去是对 block 对象的特定调用场景进行限频，我的是对某个对象、方法或类方法的任何调用进行限频。针对 Block 的 hook 可以看下我的 https://github.com/yulingtianxia/BlockHook ，基于此也可以对任意 block 的任意场景进行限频操作。

**Comment by SatanWoo** [comment]
why u so niu bi

**Comment by SatanWoo** [comment]
Cool

**Comment by yulingtianxia** [comment]
@SatanWoo 五子棋最酷
